### ISSUE TITLE
"Windows protected your PC"

### ISSUE THREAD

**Issue by OfficialWasTaken** [ThaBluNate/Serkket#1]
When downloading serkket it showed me a screen that said _"Windows protected your PC"_ 
Is there a way to bypass this?

**Comment by OfficialWasTaken** [comment]
Click "More Info" and then "Run anyway"

**Comment by OfficialWasTaken** [comment]
Click "More Info" and then "Run anyway"

**Comment by ThaBluNate** [comment]
Official, please don't open issues to specify already-documented things
You can check the documents at https://sites.google.com/view/serkket-docs
thank you
